//
//  main.swift
//  StyleKitSwiftExtractor
//
//  Created by Alsey Coleman Miller on 6/9/15.
//  Copyright (c) 2015 ColemanCDA. All rights reserved.
//

import Foundation

let inputFileName = "StyleKit.swift"

print("Loading \(inputFileName)")

let styleKitPath = NSFileManager.defaultManager().currentDirectoryPath + "/" + inputFileName

let inputText = try NSString(contentsOfFile: styleKitPath, encoding: NSUTF8StringEncoding) as String

print("Generating source code")

var sourceCode = "// This is a generated file, do not edit!\n// Generated by StyleKitSwiftExtractor, see https://github.com/colemancda/StyleKitView\n\nimport UIKit\n"

print("Extracting Canvas Names from \(inputFileName)")

let canvasNames = ExtractCanvasNames(inputText)

print("Generating StyleKitView source code")

let styleKitViewSourceCode = GenerateStyleKitViewSourceCode(canvasNames)

sourceCode.appendLine(styleKitViewSourceCode)

let styleKitViewFileName = "StyleKitView.generated.swift"

print("Saving StyleKitView.swift to disk")

let styleKitViewPath = NSFileManager.defaultManager().currentDirectoryPath + "/" + styleKitViewFileName

try sourceCode.writeToFile(styleKitViewPath, atomically: true, encoding: NSUTF8StringEncoding)

